"""Notification model added

Revision ID: 1dfab4f0edcc
Revises: eed62b868b8b
Create Date: 2024-10-08 13:31:48.058307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfab4f0edcc'
down_revision = 'eed62b868b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_title', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('sub_title')

    # ### end Alembic commands ###
