"""empty message

Revision ID: 659885f604b5
Revises: cc19d0e24d7b
Create Date: 2024-10-08 13:51:33.537011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659885f604b5'
down_revision = 'cc19d0e24d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), server_default='2024-10-08 12:51:33.248147', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
